package com.example.lms.service.rag.handler;

import dev.langchain4j.rag.content.Content;
import dev.langchain4j.data.document.Document;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * Evidence‑aware regeneration guard.  This component decides whether an
 * assistant’s draft should be regenerated by the high tier model based on
 * the quantity and diversity of retrieved evidence and the quality of the
 * initial draft.  It is deliberately fail‑soft: any exceptions thrown
 * during metadata inspection are ignored and the guard falls back to using
 * approximate heuristics.  The thresholds for evidence count and distinct
 * source count are configurable via {@code rag.guard.min-evidence-count}
 * and {@code rag.guard.min-evidence-from-distinct-sources}.  When a
 * draft appears to lack substantive information (e.g. contains phrases
 * such as “정보 없음” or is extremely short) and both thresholds are
 * satisfied the guard will return {@code true}.
 */
@Component
public class EvidenceAwareGuard {

    private final int minEvidenceCount;
    private final int minEvidenceFromDistinctSources;

    public EvidenceAwareGuard(
            @Value("${rag.guard.min-evidence-count:2}") int minEvidenceCount,
            @Value("${rag.guard.min-evidence-from-distinct-sources:1}") int minEvidenceFromDistinctSources
    ) {
        this.minEvidenceCount = minEvidenceCount;
        this.minEvidenceFromDistinctSources = minEvidenceFromDistinctSources;
    }

    /**
     * Determine whether the assistant’s draft should be regenerated.  A
     * regeneration is recommended when the draft is judged to be empty or
     * uninformative, a minimum number of evidence snippets are available and
     * the snippets originate from a sufficient number of distinct sources.
     *
     * @param webDocs    the list of web search results (may be null or empty)
     * @param vectorDocs the list of vector RAG results (may be null or empty)
     * @param draft      the assistant draft to evaluate
     * @return {@code true} if regeneration should occur, otherwise {@code false}
     */
    public boolean shouldRegenerate(List<Content> webDocs, List<Content> vectorDocs, String draft) {
        // If the draft contains information, no regeneration is needed.
        if (!looksEmptyDraft(draft)) {
            return false;
        }
        int total = 0;
        Set<String> sources = new HashSet<>();
        total += collectCounts(webDocs, sources);
        total += collectCounts(vectorDocs, sources);
        return total >= minEvidenceCount && sources.size() >= minEvidenceFromDistinctSources;
    }

    /**
     * Count the number of documents and accumulate distinct source identifiers.
     * The implementation attempts to extract a 'source' key from the content
     * metadata if available; otherwise it falls back to a hash of the text.
     */
    private int collectCounts(List<Content> docs, Set<String> sources) {
        if (docs == null || docs.isEmpty()) return 0;
        int count = 0;
        for (Content c : docs) {
            if (c == null) continue;
            count++;
            try {
                // 메타데이터에서 'source' 식별자 추출 (LangChain4j 1.0.1 규격)
                // 1) 출처 식별자는 TextSegment의 문서 메타데이터(String 키)에서 우선 추출
                var seg = c.textSegment();
                if (seg != null && seg.metadata() != null) {
                    var md = seg.metadata(); // dev.langchain4j.data.document.Metadata
                    String src = firstNonBlank(
                            md.getString("source"),                // 커스텀 인제스터에서 흔히 사용
                            md.getString("url"),                   // 웹 로더/검색기에서 흔히 사용
                            md.getString(Document.URL),            // 표준 상수
                            md.getString(Document.FILE_NAME),      // 파일 로더용
                            md.getString("filename"),
                            md.getString("path")
                    );
                    if (src != null) {
                        sources.add(src);
                        continue;
                    }
                }
            } catch (Throwable ignore) {
                // ignore and fall back below
            }
            try {
                // Fallback: use a hash of the text segment as a proxy for distinctness
                String text = c.textSegment() != null ? c.textSegment().text() : c.toString();
                if (text != null) {
                    sources.add(Integer.toString(text.hashCode()));
                }
            } catch (Throwable ignore) {
                // no-op
            }
        }
        return count;
    }
    private static String firstNonBlank(String... vals) {
        if (vals == null) return null;
        for (String v : vals) if (v != null && !v.isBlank()) return v;
        return null;
    }

    /**
     * Heuristic to determine whether a draft appears to convey no information.
     * The method trims and lower‑cases the input and looks for specific
     * phrases commonly returned by the assistant when evidence is lacking.
     * Extremely short outputs (≤5 words or ≤30 characters) are also treated
     * as empty.
     */
    private static boolean looksEmptyDraft(String s) {
        if (s == null) return true;
        String t = s.strip().toLowerCase(Locale.ROOT);
        if (t.isBlank()) return true;
        if (t.contains("정보 없음")) return true;
        if (t.contains("insufficient")) return true;
        if (t.contains("not enough information")) return true;
        if (t.contains("i don't have")) return true;
        if (t.contains("자료가 부족")) return true;
        String[] words = t.split("\\s+");
        return words.length <= 5 || t.length() <= 30;
    }
}