import java.io.File

/**
 * HOOK SENTINEL ONLY — this file is not evaluated by Gradle.
 * The active settings file is `settings.gradle` (Groovy wins when both exist;
 * `rootProject.name='src111_merge15'`, `include(':app')`). `.codex/hooks.json`
 * requires this file to exist as a root sentinel. Do not edit this file's
 * include/plugin content expecting a build effect; edit `settings.gradle`.
 *
 * Offline-friendly repository setup.
 *
 * 기본 동작:
 * - 평소엔 (온라인) Gradle Plugin Portal / Maven Central / Spring repo 를 사용합니다.
 * - `--offline` 또는 `OFFLINE_BUILD=1` 인 경우, 공용 인터넷 레포지토리는 *추가하지 않습니다*
 *   (방화벽/폐쇄망에서 네트워크 hang 방지).
 *
 * 오프라인에서 의존성/플러그인 해소를 위해서는 아래 중 하나를 준비하세요.
 * - 사내 미러(Nexus/Artifactory 등):
 *     - MAVEN_MIRROR_URL
 *     - GRADLE_PLUGIN_MIRROR_URL (없으면 보통 MAVEN_MIRROR_URL 만으로도 해결되도록 미러 구성)
 * - 로컬(동봉) Maven repo 디렉토리:
 *     - OFFLINE_MAVEN_REPO=/path/to/m2repo  또는 file:///...
 *     - 또는 프로젝트 루트의 ./offline-repo 디렉토리
 */

val explicitOffline: Boolean = System.getenv("OFFLINE_BUILD") == "1"
val offlineMode: Boolean = gradle.startParameter.isOffline || explicitOffline

fun envOrProp(envKey: String, propKey: String): String? {
    val env = System.getenv(envKey)
    if (!env.isNullOrBlank()) return env
    val prop = System.getProperty(propKey)
    if (!prop.isNullOrBlank()) return prop
    return null
}

val mavenMirrorUrl: String? = envOrProp("MAVEN_MIRROR_URL", "mavenMirrorUrl")
val offlineMavenRepo: String? = envOrProp("OFFLINE_MAVEN_REPO", "offlineMavenRepo")
val projectLocalOfflineRepo: File? = File(rootDir, "offline-repo").takeIf { it.isDirectory }

fun org.gradle.api.artifacts.dsl.RepositoryHandler.addLocalReposFirst() {
    // 1) 로컬 캐시/레포지토리를 최우선
    mavenLocal()

    // 2) 외부에서 전달된 로컬 Maven repo 디렉토리
    if (!offlineMavenRepo.isNullOrBlank()) {
        maven { url = uri(offlineMavenRepo) }
    }

    // 3) 프로젝트에 동봉한 offline-repo
    if (projectLocalOfflineRepo != null) {
        maven { url = uri(projectLocalOfflineRepo) }
    }
}

pluginManagement {
    // Gradle compiles pluginManagement before the remaining settings declarations.
    val pluginOfflineMode = gradle.startParameter.isOffline || System.getenv("OFFLINE_BUILD") == "1"
    val pluginMavenMirror = System.getenv("MAVEN_MIRROR_URL")?.takeIf { it.isNotBlank() }
        ?: System.getProperty("mavenMirrorUrl")?.takeIf { it.isNotBlank() }
    val pluginMirror = System.getenv("GRADLE_PLUGIN_MIRROR_URL")?.takeIf { it.isNotBlank() }
        ?: System.getProperty("gradlePluginMirrorUrl")?.takeIf { it.isNotBlank() }
    val pluginOfflineRepo = System.getenv("OFFLINE_MAVEN_REPO")?.takeIf { it.isNotBlank() }
        ?: System.getProperty("offlineMavenRepo")?.takeIf { it.isNotBlank() }
    val pluginLocalRepo = java.io.File(rootDir, "offline-repo").takeIf { it.isDirectory }

    repositories {
        mavenLocal()
        if (!pluginOfflineRepo.isNullOrBlank()) {
            maven { url = uri(pluginOfflineRepo) }
        }
        if (pluginLocalRepo != null) {
            maven { url = uri(pluginLocalRepo) }
        }
        if (!pluginMirror.isNullOrBlank()) {
            maven { url = uri(pluginMirror) }
        }
        if (!pluginMavenMirror.isNullOrBlank()) {
            maven { url = uri(pluginMavenMirror) }
        }

        // 온라인일 때만 공용 레포지토리 사용
        if (!pluginOfflineMode) {
            gradlePluginPortal()
            mavenCentral()
            maven { url = uri("https://repo.spring.io/release") }
        }
    }
}

dependencyResolutionManagement {
    // 레포지토리는 settings 에서 단일 관리 (재현성/오프라인 대응)
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)

    repositories {
        addLocalReposFirst()

        if (!mavenMirrorUrl.isNullOrBlank()) {
            maven { url = uri(mavenMirrorUrl) }
        }

        if (!offlineMode) {
            mavenCentral()
            maven { url = uri("https://repo.spring.io/release") }
        }
    }
}

rootProject.name = "lms-core"

include(":app")
val includeLegacyModules = providers.gradleProperty("includeLegacyModules")
    .orElse(providers.environmentVariable("INCLUDE_LEGACY_MODULES"))
    .map(String::toBoolean)
    .getOrElse(false)

if (includeLegacyModules && file("demo-1").exists()) include(":demo-1")
if (includeLegacyModules && file("demo-2").exists()) include(":demo-2")
if (includeLegacyModules && file("demo-3").exists()) include(":demo-3")
if (includeLegacyModules && file("lms-core").exists()) include(":lms-core")

// backup modules
if (includeLegacyModules && file("lms-core-backup").exists()) include(":lms-core-backup")
if (includeLegacyModules && file("demo-1-backup").exists()) include(":demo-1-backup")
if (includeLegacyModules && file("demo-2-backup").exists()) include(":demo-2-backup")
if (includeLegacyModules && file("demo-3-backup").exists()) include(":demo-3-backup")
