package com.example.lms.tools;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

class ContextPurityScriptContractTest {

    @Test
    void defaultReportModeUsesBoundedScanRootsInsteadOfWholeWorkspaceRecursion() throws Exception {
        String script = Files.readString(Path.of("tools/context_purity_score.ps1"));

        assertTrue(script.contains("[switch]$FullWorkspaceScan"));
        assertTrue(script.contains("function Get-ContextPurityReportItems"));
        assertTrue(script.contains("if ($FullWorkspaceScan)"));
        assertTrue(script.contains("app/src/main/java_clean"));
        assertTrue(script.contains("app/src/main/resources"));
        assertTrue(script.contains(".agents/skills"));
        assertTrue(script.contains("docs/ai-memory"));
        assertTrue(script.contains("agent-prompts"));
        assertFalse(script.contains("$items = Get-ChildItem -LiteralPath $workspace -Force -Recurse -File"),
                "default context purity report must not enumerate build, PatchDrop, and cache trees before filtering");
    }

    @Test
    void javaEvidenceHashingDoesNotDependOnPowerShellUtilityModuleResolution() throws Exception {
        String script = Files.readString(Path.of("tools/context_purity_score.ps1"));

        assertFalse(script.contains("Get-FileHash"),
                "Java evidence hashing must remain independent of inherited PSModulePath entries");
        assertTrue(script.contains("[System.Security.Cryptography.SHA256]::Create()"));
    }

    @Test
    void boundedReportAtomicallyWritesDeterministicDecisionTsv(@TempDir Path workspace) throws Exception {
        write(workspace.resolve("main/java/example/Active.java"), "package example; class Active {}\n");
        write(workspace.resolve("main/java/example/Leaked.class"), "generated bytecode\n");
        write(workspace.resolve("app/src/main/resources/application.yml"), "feature: true\n");
        write(workspace.resolve("agent-prompts/out/generated.prompt"), "generated\n");
        write(workspace.resolve("agent-prompts/manual-note.md"), "manual review\n");
        write(workspace.resolve("agent-prompts/legacy.bak"), "uncertain backup\n");
        write(workspace.resolve("docs/ai-memory/Dynamic_RAG_Orchestration_Platform.memory.md"),
                "canonical memory\n");
        write(workspace.resolve(".agents/skills/sample/SKILL.md"), "canonical skill\n");

        Path report = workspace.resolve("__reports__/context-purity-decisions.tsv");
        runScript(workspace);
        byte[] first = Files.readAllBytes(report);
        runScript(workspace);
        byte[] second = Files.readAllBytes(report);

        assertTrue(Arrays.equals(first, second), "same bounded workspace must produce identical TSV bytes");
        List<String> lines = Files.readAllLines(report, StandardCharsets.UTF_8);
        assertFalse(lines.isEmpty());
        assertEquals(List.of(
                        "source_path",
                        "source_set_role",
                        "active_weight",
                        "generated_score",
                        "legacy_score",
                        "duplicate_score",
                        "delete_score",
                        "memory_value",
                        "decision",
                        "reason"),
                List.of(lines.get(0).split("\\t", -1)));

        Map<String, Map<String, String>> rows = rowsByPath(lines);
        assertDecision(rows, "main\\java\\example\\Active.java", "KEEP", "active_sourceset");
        assertDecision(rows, "main\\java\\example\\Leaked.class", "DELETE", "generated_artifact");
        assertDecision(rows, "app\\src\\main\\resources\\application.yml", "KEEP", "active_sourceset");
        assertDecision(rows, "agent-prompts\\out\\generated.prompt", "DELETE", "generated_artifact");
        assertDecision(rows, "agent-prompts\\manual-note.md", "EVIDENCE_NEEDED", "needs_owner_review");
        assertDecision(rows, "agent-prompts\\legacy.bak", "QUARANTINE", "uncertain_legacy_artifact");
        assertDecision(rows,
                "docs\\ai-memory\\Dynamic_RAG_Orchestration_Platform.memory.md",
                "KEEP",
                "canonical_memory_doc");
        assertDecision(rows, ".agents\\skills\\sample\\SKILL.md", "KEEP", "canonical_skill");

        Set<String> allowed = Set.of("KEEP", "DELETE", "QUARANTINE", "EVIDENCE_NEEDED");
        assertTrue(rows.values().stream().allMatch(row -> allowed.contains(row.get("decision"))));
        assertTrue(rows.values().stream().noneMatch(row -> "KEEP_AND_INGEST".equals(row.get("decision"))));
        try (var files = Files.list(report.getParent())) {
            assertTrue(files.noneMatch(path -> {
                        String name = path.getFileName().toString();
                        return name.contains(".tmp-") || name.contains(".backup-");
                    }),
                    "atomic writer must not leave temporary or backup report files");
        }
    }

    @Test
    void boundedReportClassifiesExactAndDivergentFqcnEvidence(@TempDir Path workspace) throws Exception {
        String exactSource = "package example; public class ExactDuplicate {}\n";
        write(workspace.resolve("main/java/example/ExactDuplicate.java"), exactSource);
        write(workspace.resolve("app/src/main/java/example/ExactDuplicate.java"), exactSource);

        write(workspace.resolve("main/java/example/DivergentDuplicate.java"),
                "package example; public class DivergentDuplicate { int value() { return 1; } }\n");
        write(workspace.resolve("lms-core/src/main/java/example/DivergentDuplicate.java"),
                "package example; public class DivergentDuplicate { int value() { return 2; } }\n");

        write(workspace.resolve("main/java/example/AppShadow.java"),
                "package example; public class AppShadow { int value() { return 1; } }\n");
        write(workspace.resolve("app/src/main/java_clean/example/AppShadow.java"),
                "package example; public class AppShadow { int value() { return 2; } }\n");

        write(workspace.resolve("main/java/example/MixedDuplicate.java"),
                "package example; public class MixedDuplicate { int value() { return 1; } }\n");
        String mixedAppSource =
                "package example; public class MixedDuplicate { int value() { return 2; } }\n";
        write(workspace.resolve("app/src/main/java_clean/example/MixedDuplicate.java"), mixedAppSource);
        write(workspace.resolve("app/src/main/java/example/MixedDuplicate.java"), mixedAppSource);

        write(workspace.resolve("main/java/canonical/CaseVariant.java"),
                "package example.casevariant; public class CaseVariant {}\n");
        write(workspace.resolve("app/src/main/java/inactive/CaseVariant.java"),
                "package example.CaseVariant; public class CaseVariant {}\n");

        write(workspace.resolve("main/java/canonical/SameActive.java"),
                "package example.active; public class SameActive { int value() { return 1; } }\n");
        write(workspace.resolve("main/java/shadow/SameActive.java"),
                "package example.active; public class SameActive { int value() { return 2; } }\n");
        write(workspace.resolve("app/src/main/java_clean/canonical/AppActive.java"),
                "package example.appactive; public class AppActive { int value() { return 1; } }\n");
        write(workspace.resolve("app/src/main/java_clean/shadow/AppActive.java"),
                "package example.appactive; public class AppActive { int value() { return 2; } }\n");

        runScript(workspace);
        Map<String, Map<String, String>> rows = rowsByPath(Files.readAllLines(
                workspace.resolve("__reports__/context-purity-decisions.tsv"),
                StandardCharsets.UTF_8));

        assertDecision(rows, "main\\java\\example\\ExactDuplicate.java", "KEEP", "active_sourceset");
        assertDecision(rows,
                "app\\src\\main\\java\\example\\ExactDuplicate.java",
                "QUARANTINE",
                "exact_duplicate_non_active_excluded");
        assertField(rows, "app\\src\\main\\java\\example\\ExactDuplicate.java", "duplicate_score", "1.00");

        assertDecision(rows, "main\\java\\example\\DivergentDuplicate.java", "KEEP", "active_sourceset");
        assertDecision(rows,
                "lms-core\\src\\main\\java\\example\\DivergentDuplicate.java",
                "EVIDENCE_NEEDED",
                "fqcn_content_divergence_evidence_needed_verify_with_checkSourceSetHygiene");
        assertField(rows,
                "lms-core\\src\\main\\java\\example\\DivergentDuplicate.java",
                "duplicate_score",
                "1.00");

        assertDecision(rows, "main\\java\\example\\AppShadow.java", "KEEP", "active_sourceset");
        assertDecision(rows,
                "app\\src\\main\\java_clean\\example\\AppShadow.java",
                "EVIDENCE_NEEDED",
                "fqcn_content_divergence_evidence_needed_verify_with_app_duplicate_excludes");
        assertField(rows,
                "app\\src\\main\\java_clean\\example\\AppShadow.java",
                "duplicate_score",
                "1.00");

        assertDecision(rows, "main\\java\\example\\MixedDuplicate.java", "KEEP", "active_sourceset");
        assertDecision(rows,
                "app\\src\\main\\java_clean\\example\\MixedDuplicate.java",
                "EVIDENCE_NEEDED",
                "fqcn_content_divergence_evidence_needed_verify_with_app_duplicate_excludes");
        assertDecision(rows,
                "app\\src\\main\\java\\example\\MixedDuplicate.java",
                "QUARANTINE",
                "exact_duplicate_non_active_excluded");
        assertField(rows,
                "app\\src\\main\\java\\example\\MixedDuplicate.java",
                "duplicate_score",
                "1.00");

        assertFalse(rows.containsKey("app\\src\\main\\java\\inactive\\CaseVariant.java"),
                "Java FQCN grouping must be ordinal case-sensitive");

        assertDecision(rows, "main\\java\\canonical\\SameActive.java", "KEEP", "active_sourceset");
        assertDecision(rows,
                "main\\java\\shadow\\SameActive.java",
                "EVIDENCE_NEEDED",
                "fqcn_content_divergence_evidence_needed_verify_with_checkSourceSetHygiene");
        assertField(rows, "main\\java\\shadow\\SameActive.java", "duplicate_score", "1.00");

        assertDecision(rows,
                "app\\src\\main\\java_clean\\canonical\\AppActive.java",
                "KEEP",
                "active_sourceset");
        assertDecision(rows,
                "app\\src\\main\\java_clean\\shadow\\AppActive.java",
                "EVIDENCE_NEEDED",
                "fqcn_content_divergence_evidence_needed_verify_with_checkSourceSetHygiene");
        assertField(rows,
                "app\\src\\main\\java_clean\\shadow\\AppActive.java",
                "duplicate_score",
                "1.00");
    }

    @Test
    void boundedReportDetectsPackageInUtf8BomJavaEvidence(@TempDir Path workspace) throws Exception {
        String source = "package example; public class BomDuplicate {}\n";
        writeUtf8Bom(workspace.resolve("main/java/example/BomDuplicate.java"), source);
        write(workspace.resolve("app/src/main/java/example/BomDuplicate.java"), source);

        runScript(workspace);
        Map<String, Map<String, String>> rows = rowsByPath(Files.readAllLines(
                workspace.resolve("__reports__/context-purity-decisions.tsv"),
                StandardCharsets.UTF_8));

        assertDecision(rows, "main\\java\\example\\BomDuplicate.java", "KEEP", "active_sourceset");
        assertDecision(rows,
                "app\\src\\main\\java\\example\\BomDuplicate.java",
                "EVIDENCE_NEEDED",
                "fqcn_content_divergence_evidence_needed_verify_with_checkSourceSetHygiene");
        assertField(rows, "app\\src\\main\\java\\example\\BomDuplicate.java", "duplicate_score", "1.00");
    }

    @Test
    void gradleTaskDependsOnSourceSetProofAndDeclaresDecisionOutput() throws Exception {
        String build = Files.readString(Path.of("build.gradle.kts"));

        assertTrue(build.contains("tasks.register<Exec>(\"contextPurityReport\")"));
        assertTrue(build.contains("dependsOn(\"checkSourceSetHygiene\")"));
        assertTrue(build.contains("tools/context_purity_score.ps1"));
        assertTrue(build.contains("outputs.file(contextPurityDecisionsOutput)"));
        assertTrue(build.contains("\"-OutputPath\""));
        assertTrue(build.contains("doNotTrackState("),
                "bounded report must rerun without Gradle snapshotting access-restricted support roots");
        String script = Files.readString(Path.of("tools/context_purity_score.ps1"));
        assertTrue(script.contains("-ErrorVariable scanErrors"));
        assertTrue(script.contains("evidence_needed: context purity scan incomplete"));
        assertTrue(script.contains("gradle/wrapper/gradle-wrapper.jar"));
    }

    @ParameterizedTest
    @CsvSource({"root,true", "root,false", "app,true", "app,false"})
    void strictRetainedSourcesRejectSameOwnerDuplicates(
            String owner, boolean identical, @TempDir Path workspace) throws Exception {
        String prefix = owner.equals("root") ? "main/java/" : "app/src/main/java_clean/";
        String first = prefix + "first/Duplicate.java";
        String second = prefix + "second/Duplicate.java";
        write(workspace.resolve(first), "package fixture; public class Duplicate {}\n");
        write(workspace.resolve(second), identical
                ? "package fixture; public class Duplicate {}\n"
                : "package fixture; public class Duplicate { int changed; }\n");

        ScriptResult result = runStrictScript(workspace, owner, List.of(first, second));

        assertTrue(result.exitCode() != 0, "retained duplicate must reject");
        assertTrue(result.output().contains("SOURCE_HYGIENE_DUPLICATE"), result.output());
        assertFalse(Files.exists(workspace.resolve("__reports__/context-purity-decisions.tsv")));
    }

    @Test
    void strictRetainedSourcesIgnoreExcludedAndInactiveCopies(@TempDir Path workspace) throws Exception {
        String active = "main/java/first/Duplicate.java";
        String source = "package fixture; public class Duplicate {}\n";
        write(workspace.resolve(active), source);
        write(workspace.resolve("main/java/excluded/Duplicate.java"), source);
        write(workspace.resolve("app/src/main/java/inactive/Duplicate.java"), source);

        ScriptResult result = runStrictScript(workspace, "root", List.of(active));

        assertEquals(0, result.exitCode(), result.output());
        assertTrue(result.output().contains("retainedFiles=1"), result.output());
        assertFalse(Files.exists(workspace.resolve("__reports__/context-purity-decisions.tsv")));
    }

    @Test
    void strictRetainedSourcesPreserveCaseSensitiveFqcnAndBom(@TempDir Path workspace) throws Exception {
        String first = "main/java/first/Example.java";
        String second = "main/java/second/Example.java";
        writeUtf8Bom(workspace.resolve(first), "package fixture.upper; public class Example {}\n");
        write(workspace.resolve(second), "package fixture.Upper; public class Example {}\n");

        ScriptResult result = runStrictScript(workspace, "root", List.of(first, second));

        assertEquals(0, result.exitCode(), result.output());
        assertTrue(result.output().contains("retainedFiles=2"), result.output());
    }

    @ParameterizedTest
    @CsvSource({"../outside.java", "app/src/main/java/inactive/Example.java"})
    void strictRetainedSourcesRejectPathsOutsideDeclaredOwner(
            String source, @TempDir Path workspace) throws Exception {
        ScriptResult result = runStrictScript(workspace, "root", List.of(source));

        assertTrue(result.exitCode() != 0);
        assertTrue(result.output().contains("SOURCE_HYGIENE_PATH"), result.output());
    }

    private record ScriptResult(int exitCode, String output) {}

    private static ScriptResult runStrictScript(Path workspace, String owner, List<String> files)
            throws Exception {
        Path manifest = workspace.resolve("retained-sources.json");
        String entries = files.stream().map(path -> "\"" + path + "\"")
                .collect(java.util.stream.Collectors.joining(","));
        write(manifest, "{\"" + owner + "\":[" + entries + "]}");
        Path log = workspace.resolve("strict-output.log");
        Process process = new ProcessBuilder("powershell", "-NoProfile", "-ExecutionPolicy", "Bypass",
                "-File", Path.of("tools/context_purity_score.ps1").toAbsolutePath().toString(),
                "-Workspace", workspace.toString(), "-ActiveSourceManifest", manifest.toString())
                .redirectErrorStream(true).redirectOutput(log.toFile()).start();
        try {
            assertTrue(process.waitFor(30, TimeUnit.SECONDS), "strict source verification timed out");
            return new ScriptResult(process.exitValue(),
                    new String(Files.readAllBytes(log), StandardCharsets.UTF_8));
        } finally {
            if (process.isAlive()) {
                process.destroyForcibly();
                process.waitFor(5, TimeUnit.SECONDS);
            }
        }
    }

    private static void runScript(Path workspace) throws Exception {
        Path script = Path.of("tools/context_purity_score.ps1").toAbsolutePath();
        Process process = new ProcessBuilder(
                "powershell",
                "-NoProfile",
                "-ExecutionPolicy",
                "Bypass",
                "-File",
                script.toString(),
                "-Workspace",
                workspace.toString(),
                "-MaxItems",
                "100")
                .redirectErrorStream(true)
                .start();
        boolean finished = process.waitFor(30, TimeUnit.SECONDS);
        if (!finished) {
            process.destroyForcibly();
        }
        String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
        assertTrue(finished, "context purity script timed out: " + output);
        assertEquals(0, process.exitValue(), output);
    }

    private static Map<String, Map<String, String>> rowsByPath(List<String> lines) {
        List<String> header = List.of(lines.get(0).split("\\t", -1));
        Map<String, Map<String, String>> rows = new LinkedHashMap<>();
        for (String line : lines.subList(1, lines.size())) {
            List<String> values = new ArrayList<>(List.of(line.split("\\t", -1)));
            assertEquals(header.size(), values.size(), line);
            Map<String, String> row = new LinkedHashMap<>();
            for (int i = 0; i < header.size(); i++) {
                row.put(header.get(i), values.get(i));
            }
            rows.put(row.get("source_path"), row);
        }
        return rows;
    }

    private static void assertDecision(
            Map<String, Map<String, String>> rows,
            String path,
            String decision,
            String reason) {
        Map<String, String> row = rows.get(path);
        assertNotNull(row, path);
        assertEquals(decision, row.get("decision"), path);
        assertEquals(reason, row.get("reason"), path);
    }

    private static void assertField(
            Map<String, Map<String, String>> rows,
            String path,
            String field,
            String expected) {
        Map<String, String> row = rows.get(path);
        assertNotNull(row, path);
        assertEquals(expected, row.get(field), path + " field=" + field);
    }

    private static void write(Path path, String content) throws IOException {
        Files.createDirectories(path.getParent());
        Files.writeString(path, content, StandardCharsets.UTF_8);
    }

    private static void writeUtf8Bom(Path path, String content) throws IOException {
        Files.createDirectories(path.getParent());
        byte[] source = content.getBytes(StandardCharsets.UTF_8);
        byte[] bytes = new byte[source.length + 3];
        bytes[0] = (byte) 0xEF;
        bytes[1] = (byte) 0xBB;
        bytes[2] = (byte) 0xBF;
        System.arraycopy(source, 0, bytes, 3, source.length);
        Files.write(path, bytes);
    }
}
