features:
  telemetry:
    virtual-point:
      enabled: false
  alias:
    corrector:
      enabled: false
  mpc:
    enabled: false

telemetry:
  virtual-point:
    path: /var/log/app/virt/virt_points.ndjson

# NineTile alias corrector
alias:
  corrector:
    enabled: true


# Optional adapter to bridge legacy packages
adapter:
  rag-light:
    enabled: false
