spring:
  config:
    activate:
      on-profile: secrets

search:
  brave:
    enabled: true
    api-key: "<REDACTED>"

upstash:
  vector:
    rest-url: "https://<${GENERIC_LONG_TOKEN}>"
    api-key: "<REDACTED>"
    namespace: "aw-default"
    read-only: true

llm:
  groq:
    key: "${KEY}"