spring:
  config:
    activate:
      on-profile: secrets
  autoconfigure:
    exclude:
    - dev.langchain4j.spring.AiAutoConfiguration
    - dev.langchain4j.spring.autoconfigure.LangChain4jAutoConfiguration
    - dev.langchain4j.service.spring.AiServicesAutoConfiguration
    - dev.langchain4j.model.openai.spring.autoconfigure.OpenAiAutoConfiguration
search:
  brave:
    enabled: true
    api-key: ""
local-llm:
  enabled: false
openai:
  api:
    key: ""
upstash:
  vector:
    rest-url: https://<YOUR_UPSTASH_VECTOR_ENDPOINT>
    api-key: ""
    namespace: aw-default
    read-only: true