# Nova Protocol — Hypernova Plan (v1)
# Purpose: high-risk/high-return retrieval with tail-weighted fusion + CVaR emphasis
meta:
  id: hypernova.v1
  description: "Aggressive recall with TWPM+CVaR fusion, DPP diversity, strict safety gates."
  owner: "ops@abandonware.ai"
stages:
  - name: preflight_safety
    gates:
      - AutorunPreflightGate{ require_official_sources=false, allow_rulebreak=false }
      - PIISanitizer{ mode=scan }
  - name: expand_queries
    handlers:
      - SelfAskPlanner{ branches=12, temperature=0.9 }
      - ExtremeZSystemHandler{ bursts=18, parallel=true }
  - name: retrieval
    handlers:
      - AnalyzeWebSearchRetriever{ webTopK=24, intent=recency }
      - LangChainRAGService{ ragTopK=12 }
      - KnowledgeGraphHandler{ enabled=true }
  - name: condense_refine
    handlers:
      - AngerOverdriveNarrower{ anchor_mode=auto, stages=[48,32,16,8] }
      - DppDiversityReranker{ size=10, lambda=0.7 }
      - OnnxCrossEncoderReranker{ max=8, threshold=0.15 }
  - name: fuse_and_score
    handlers:
      - TailWeightedPowerMeanFuser{ p_base=2.0, tail_q=0.15 }
      - CvarAggregator{ alpha=0.15, mix=0.5 }
      - ScoreCalibrator{ mode=prob_fallback }
      - BodeClamp{ gain=0.85 }
  - name: finalize
    gates:
      - CitationGate{ min_citations=3 }
      - FinalSigmoidGate{ k=10.0, x0=0.85 }
    output:
      prompt_builder: PromptBuilder{ mode=structured, evidence=true }
      trace: true

probe:
  search:
    enabled: false
  admin-token: ''


retrieval:
  vector:
    enabled: true