package com.example.lms.domain.enums;

/**
 * Enumeration of available translation routes.
 *
 * <p>Routes represent the origin of a translation result.  The values
 * correspond to the various backends or strategies used by the
 * {@code AdaptiveTranslationService} and related components.  When
 * adding new values update the service code accordingly.</p>
 */
public enum TranslationRoute {
    /** Translation comes from the in‑memory translation memory store. */
    MEMORY,
    /** Translation via Google Translate or similar generic provider. */
    GT,
    /** Translation generated by a Gemini model. */
    GEMINI,
    /** Translation failed or could not be produced. */
    FAILED,
    /** Translation produced by an LLM akin to GPT‑3.5. */
    GPT_3_5,
    /** Translation produced by an LLM akin to GPT‑4. */
    GPT_4
}