"""Generate .agents/rules/agents-md-overflow-index.md (awx.agy-rules-overflow.v1).

agy loads only the first ~24,000 bytes of AGENTS.md. This tool lists every
`## ` section that starts at/after the byte limit (or straddles it) with its
line number and the section's docs/agents-rules/*.md pointer (or a <=120-char
first-line summary when the section has no doc link). Section bodies are NOT
copied — the index is a pointer, never a mirror.

Usage:
    python -B scripts\\agy_rules_overflow_index.py [--write] [--quiet]
    python -B scripts\\agy_rules_overflow_index.py --check   # exit 0 fresh / 3 stale
"""
import argparse
import hashlib
import os
import re
import sys

MAX_BYTES = 4096
SECTION_RE = re.compile(rb"(?m)^## .+$")
DOCLINK_RE = re.compile(r"docs/agents-rules/[A-Za-z0-9_.\-]+\.md")

HEADER = """---
trigger: always_on
---

<!-- auto-generated by scripts/agy_rules_overflow_index.py - do not edit -->
# AGENTS.md overflow index (agy sees only the first {limit} bytes)

agy rule loader truncates AGENTS.md past {limit} bytes. These `## ` sections
live past the cut ({sha}); read the linked doc or the section in AGENTS.md.
"""


def find_overflow_sections(data, limit):
    """Return [(byte_start, line_no, title, body_text)] for sections at/after
    `limit` or straddling it."""
    matches = list(SECTION_RE.finditer(data))
    total = len(data)
    out = []
    for i, m in enumerate(matches):
        end = matches[i + 1].start() if i + 1 < len(matches) else total
        if m.start() < limit and end <= limit:
            continue
        line_no = data[: m.start()].count(b"\n") + 1
        title = m.group().decode("utf-8", "replace").strip()
        body = data[m.end():end].decode("utf-8", "replace")
        out.append((m.start(), line_no, title, body))
    return out


def first_line_summary(body):
    for line in body.splitlines():
        line = line.strip()
        if not line or line.startswith("<!--"):
            continue
        line = re.sub(r"^[-*># ]+", "", line).strip()
        line = re.sub(r"\s+", " ", line)
        if line:
            return line[:120]
    return ""


def entry_for(section):
    _start, line_no, title, body = section
    m = DOCLINK_RE.search(body)
    ref = m.group(0) if m else first_line_summary(body)
    ref = ref.replace("`", "'")
    return "- L%d `%s` — %s" % (line_no, title[:90], ref)


def build(data, limit):
    sha = hashlib.sha256(data).hexdigest()[:12]
    sections = find_overflow_sections(data, limit)
    head = HEADER.format(limit=limit, sha=sha)
    entries = [entry_for(s) for s in sections]
    text = head + "\n" + "\n".join(entries) + "\n"
    if len(text.encode("utf-8")) > MAX_BYTES:
        entries = [entry_for(s)[:150] for s in sections]
        text = head + "\n" + "\n".join(entries) + "\n"
    return text, sections


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=".")
    parser.add_argument("--file", default=None, help="default <root>/AGENTS.md")
    parser.add_argument("--out", default=None,
                        help="default <root>/.agents/rules/agents-md-overflow-index.md")
    parser.add_argument("--limit", type=int, default=24000)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)

    agents = args.file or os.path.join(args.root, "AGENTS.md")
    out_path = args.out or os.path.join(args.root, ".agents", "rules",
                                        "agents-md-overflow-index.md")
    try:
        with open(agents, "rb") as fh:
            data = fh.read()
    except OSError as exc:
        print("[overflow-index] cannot read %s: %s" % (agents, exc), file=sys.stderr)
        return 2

    text, sections = build(data, args.limit)
    if len(text.encode("utf-8")) > MAX_BYTES:
        print("[overflow-index] generated >%d bytes" % MAX_BYTES, file=sys.stderr)
        return 4

    if args.check:
        try:
            with open(out_path, "r", encoding="utf-8") as fh:
                current = fh.read()
        except OSError:
            current = None
        if current == text:
            if not args.quiet:
                print("[overflow-index] fresh (%d sections, limit=%d)" % (len(sections), args.limit))
            return 0
        if not args.quiet:
            print("[overflow-index] STALE or missing: %s" % out_path, file=sys.stderr)
        return 3

    # default and --write both write (idempotent)
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    if not args.quiet:
        print("[overflow-index] wrote %s (%d sections, %d bytes, limit=%d)"
              % (out_path, len(sections), len(text.encode("utf-8")), args.limit))
    return 0


if __name__ == "__main__":
    sys.exit(main())
