param(
    [int]$Port = 18124,
    [int]$ManagementPort = 18125,
    [int]$StartupTimeoutSeconds = 120,
    [int]$CollectorTimeoutSeconds = 60
)

$ErrorActionPreference = "Stop"

$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$Gradle = Join-Path $Root "gradlew.bat"
if (-not (Test-Path $Gradle)) {
    throw "gradlew.bat not found under repo root"
}

$TempRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("awx-learning-ops-collector-smoke-" + [guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Force -Path $TempRoot | Out-Null
$DbFile = (Join-Path $TempRoot "ops-ledger-db").Replace('\', '/')
$DbUrl = "jdbc:h2:file:$DbFile;MODE=MariaDB;DATABASE_TO_UPPER=false"
$CollectorFile = Join-Path $TempRoot "learning-ops-curation.jsonl"
$SeedSecret = "collector-smoke-secret-" + [guid]::NewGuid().ToString("N")
$AdminToken = "collector-smoke-admin-" + [guid]::NewGuid().ToString("N")
$OriginalEnv = @{}

function Redact-Text([string]$Text) {
    if ($null -eq $Text) { return "" }
    $out = $Text
    foreach ($secret in @($TempRoot, $DbFile, $CollectorFile, $SeedSecret, $AdminToken)) {
        if (-not [string]::IsNullOrWhiteSpace($secret)) {
            $out = $out -replace [regex]::Escape($secret), "<redacted>"
        }
    }
    return $out
}

function Hash-Value([string]$Value) {
    if ([string]::IsNullOrWhiteSpace($Value)) { return "" }
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($Value.Trim())
        $hash = $sha.ComputeHash($bytes)
        $hex = -join ($hash | ForEach-Object { $_.ToString("x2") })
        return "hash:" + $hex.Substring(0, 12)
    } finally {
        $sha.Dispose()
    }
}

function Find-H2Jar {
    $candidates = @(
        "D:\gradle-cache\caches\modules-2\files-2.1\com.h2database\h2",
        (Join-Path $env:USERPROFILE ".gradle\caches\modules-2\files-2.1\com.h2database\h2")
    )
    foreach ($root in $candidates) {
        if (Test-Path $root) {
            $jar = Get-ChildItem -LiteralPath $root -Recurse -Filter "h2-*.jar" -ErrorAction SilentlyContinue |
                    Sort-Object FullName -Descending |
                    Select-Object -First 1
            if ($null -ne $jar) {
                return $jar.FullName
            }
        }
    }
    throw "[AWX][learning-ops-smoke] evidence_needed: H2 runtime jar missing / run .\gradlew.bat test or verify Gradle cache"
}

function Sql-String([string]$Value) {
    return "'" + ($Value -replace "'", "''") + "'"
}

function New-SeedDatabase {
    $h2 = Find-H2Jar
    $seedSql = Join-Path $TempRoot "seed-rag-ops-ledger.sql"
    $sourceCounts = @{ attempted = 3; accepted = 1; resultCount = 0 } | ConvertTo-Json -Compress
    $quality = @{
        trainDecision = "BLOCK_RETRAIN"
        vectorDecision = "REVIEW"
        rawQuery = $SeedSecret
    } | ConvertTo-Json -Compress
    $matrix = @{
        "q_gpu_hardware_pressure" = 0.71
        "uaw.gpu-hardware.status" = "ok"
        "uaw.gpu-hardware.admission.status" = "degraded"
        "uaw.gpu-hardware.admission.reason" = "gpu_memory_pressure"
        "uaw.gpu-hardware.admission.pressureLevel" = "warn"
        "uaw.gpu-hardware.admission.retrainAllowed" = $false
        "ownerToken" = $SeedSecret
    } | ConvertTo-Json -Compress
    $sql = @"
CREATE TABLE IF NOT EXISTS rag_ops_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version BIGINT NULL,
  run_id VARCHAR(96) NOT NULL,
  entry_type VARCHAR(32) NOT NULL,
  session_hash VARCHAR(64) NULL,
  request_hash VARCHAR(64) NULL,
  query_hash VARCHAR(64) NULL,
  query_length INT NULL,
  plan_id VARCHAR(128) NULL,
  strategy_name VARCHAR(128) NULL,
  resource_tier VARCHAR(32) NULL,
  source_counts_json CLOB NULL,
  quality_json CLOB NULL,
  vector_json CLOB NULL,
  kg_json CLOB NULL,
  matrix_json CLOB NULL,
  decision VARCHAR(32) NULL,
  failure_class VARCHAR(64) NULL,
  hotspot VARCHAR(64) NULL,
  latency_ms BIGINT NULL,
  created_at TIMESTAMP NOT NULL
);
INSERT INTO rag_ops_ledger (
  run_id, entry_type, session_hash, request_hash, plan_id, strategy_name, resource_tier,
  source_counts_json, quality_json, vector_json, kg_json, matrix_json,
  decision, failure_class, hotspot, latency_ms, created_at
) VALUES (
  'collector-smoke-run', 'AUTOLEARN_CYCLE', 'hash-session', 'hash-request',
  'autolearn', 'uaw-autolearn', 'background',
  $(Sql-String $sourceCounts), $(Sql-String $quality), '{}', '{}', $(Sql-String $matrix),
  'BLOCK_RETRAIN', 'gpu_hardware_pressure', 'gpu_hardware', NULL, CURRENT_TIMESTAMP()
);
"@
    [System.IO.File]::WriteAllText($seedSql, $sql, [System.Text.UTF8Encoding]::new($false))
    & java -cp $h2 org.h2.tools.RunScript -url $DbUrl -user sa -script $seedSql
    if ($LASTEXITCODE -ne 0) {
        throw "[AWX][learning-ops-smoke] H2 seed failed exit=$LASTEXITCODE"
    }
}

function Set-SmokeEnvValue([string]$Name, [string]$Value) {
    if (-not $OriginalEnv.ContainsKey($Name)) {
        $OriginalEnv[$Name] = [Environment]::GetEnvironmentVariable($Name, "Process")
    }
    [Environment]::SetEnvironmentVariable($Name, $Value, "Process")
}

function Set-SmokeEnv {
    Set-SmokeEnvValue "SPRING_PROFILES_ACTIVE" "macmini-control-plane"
    Set-SmokeEnvValue "SERVER_PORT" ([string]$Port)
    Set-SmokeEnvValue "MANAGEMENT_SERVER_PORT" ([string]$ManagementPort)
    Set-SmokeEnvValue "SERVER_SSL_ENABLED" "false"
    Set-SmokeEnvValue "MACMINI_DB_URL" $DbUrl
    Set-SmokeEnvValue "MACMINI_JPA_DDL_AUTO" "update"
    Set-SmokeEnvValue "MACMINI_SQL_INIT_MODE" "never"
    Set-SmokeEnvValue "MACMINI_RAG_OPS_LEDGER_ENABLED" "true"
    Set-SmokeEnvValue "MACMINI_RAG_OPS_LEDGER_CAPTURE_RAG" "true"
    Set-SmokeEnvValue "MACMINI_RAG_OPS_LEDGER_CAPTURE_AUTOLEARN" "true"
    Set-SmokeEnvValue "MACMINI_LEARNING_OPS_COLLECTOR_ENABLED" "true"
    Set-SmokeEnvValue "MACMINI_LEARNING_OPS_COLLECTOR_OUTPUT_PATH" $CollectorFile
    Set-SmokeEnvValue "MACMINI_LEARNING_OPS_COLLECTOR_INITIAL_DELAY_MS" "1000"
    Set-SmokeEnvValue "MACMINI_LEARNING_OPS_COLLECTOR_INTERVAL_MS" "5000"
    Set-SmokeEnvValue "MACMINI_LEARNING_OPS_COLLECTOR_MAX_ITEMS" "5"
    Set-SmokeEnvValue "MACMINI_LEARNING_OPS_COLLECTOR_MAX_OVERVIEW_LIMIT" "20"
    Set-SmokeEnvValue "MACMINI_DATASET_API_ENABLED" "false"
    Set-SmokeEnvValue "MACMINI_DATASET_API_KEY" ""
    Set-SmokeEnvValue "MACMINI_AUTOLEARN_ENABLED" "false"
    Set-SmokeEnvValue "MACMINI_AUTOLEARN_IDLE_TRIGGER_ENABLED" "false"
    Set-SmokeEnvValue "MACMINI_AUTOLEARN_RETRAIN_ENABLED" "false"
    Set-SmokeEnvValue "MACMINI_DESKTOP_GPU_GATEWAY_ENABLED" "false"
    Set-SmokeEnvValue "LOCAL_LLM_AUTOSTART" "false"
    Set-SmokeEnvValue "LOCAL_LLM_WARMUP_ENABLED" "false"
    Set-SmokeEnvValue "DOMAIN_ALLOWLIST_ADMIN_TOKEN" $AdminToken
    Set-SmokeEnvValue "DOMAIN_ALLOWLIST_ADMIN_TOKEN_REQUIRED" "true"
}

function Clear-SmokeEnv {
    foreach ($entry in $OriginalEnv.GetEnumerator()) {
        [Environment]::SetEnvironmentVariable($entry.Key, $entry.Value, "Process")
    }
    $OriginalEnv.Clear()
}

function Get-SmokeGradleArguments {
    $args = @("bootRun", "--rerun-tasks", "--no-daemon", "-x", "test")
    if (-not [string]::IsNullOrWhiteSpace($env:AWX_PROJECT_CACHE_DIR)) {
        $args += @("--project-cache-dir", $env:AWX_PROJECT_CACHE_DIR)
    }
    return $args
}

function Assert-NoGradleCollision([string]$Stage) {
    $rootPattern = [regex]::Escape($Root)
    $conflicts = @(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue |
            Where-Object {
                $_.ProcessId -ne $PID -and
                $_.CommandLine -match $rootPattern -and
                ($_.CommandLine -match 'gradlew\.bat|GradleWrapperMain|GradleMain|bootRun' -or
                 $_.CommandLine -match 'build\\classes\\java\\main.*com\.example\.lms\.LmsApplication')
            } |
            Select-Object -First 5 -Property ProcessId, Name, CommandLine)
    if ($conflicts.Count -gt 0) {
        $summary = ($conflicts | ForEach-Object { "pid=$($_.ProcessId) name=$($_.Name)" }) -join "; "
        throw "[AWX][learning-ops-smoke] gradle-cache-collision stage=$Stage conflictingProcesses=$summary"
    }
}

function Start-SmokeApp {
    Assert-NoGradleCollision "before-bootRun"
    $outLog = Join-Path $TempRoot "app.out.log"
    $errLog = Join-Path $TempRoot "app.err.log"
    $proc = Start-Process -FilePath $Gradle `
        -ArgumentList (Get-SmokeGradleArguments) `
        -WorkingDirectory $Root `
        -RedirectStandardOutput $outLog `
        -RedirectStandardError $errLog `
        -WindowStyle Hidden `
        -PassThru
    return @{ Process = $proc; OutLog = $outLog; ErrLog = $errLog }
}

function Stop-SmokeApp($App) {
    if ($null -eq $App -or $null -eq $App.Process) { return }
    $proc = $App.Process
    if (-not $proc.HasExited) {
        & taskkill.exe /PID $proc.Id /T /F | Out-Null
        $proc.WaitForExit(10000) | Out-Null
    }
}

function Tail-Log($Path) {
    if (-not (Test-Path $Path)) { return "" }
    return Redact-Text ((Get-Content -LiteralPath $Path -Tail 100 -ErrorAction SilentlyContinue) -join [Environment]::NewLine)
}

function Wait-ForHttp($App) {
    $deadline = (Get-Date).AddSeconds($StartupTimeoutSeconds)
    $url = "http://127.0.0.1:$ManagementPort/actuator/health"
    while ((Get-Date) -lt $deadline) {
        if ($App.Process.HasExited) {
            throw "[AWX][learning-ops-smoke] app exited during startup`n$(Tail-Log $App.OutLog)`n$(Tail-Log $App.ErrLog)"
        }
        try {
            Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 2 | Out-Null
            return
        } catch {
            Start-Sleep -Seconds 2
        }
    }
    throw "[AWX][learning-ops-smoke] startup timeout`n$(Tail-Log $App.OutLog)`n$(Tail-Log $App.ErrLog)"
}

function Invoke-Json([string]$Path) {
    try {
        $resp = Invoke-WebRequest `
            -Uri "http://127.0.0.1:$Port$Path" `
            -Headers @{ "X-Admin-Token" = $AdminToken } `
            -UseBasicParsing `
            -TimeoutSec 15
    } catch {
        $response = $_.Exception.Response
        if ($null -eq $response) { throw }
        $responseContentType = ([string]$response.ContentType -replace '[^A-Za-z0-9/;=.+_-]', '_')
        throw "[AWX][learning-ops-smoke] diagnostics-auth-or-non-json status=$([int]$response.StatusCode) contentType=$responseContentType contentLength=$($response.ContentLength) loginHtml=unknown adminTokenPresent=true"
    }

    $content = [string]$resp.Content
    $contentType = [string]$resp.Headers["Content-Type"]
    $isJson = $contentType -match '(?i)^\s*application/(?:[^;\s]+\+)?json(?:\s*;|$)'
    if (-not $isJson) {
        $safeContentType = ($contentType -replace '[^A-Za-z0-9/;=.+_-]', '_')
        $loginHtml = $content -match '(?is)^\s*(?:<!doctype\s+html|<html)'
        throw "[AWX][learning-ops-smoke] diagnostics-auth-or-non-json status=$([int]$resp.StatusCode) contentType=$safeContentType contentLength=$($content.Length) loginHtml=$($loginHtml.ToString().ToLowerInvariant()) adminTokenPresent=true"
    }

    try {
        $body = $content | ConvertFrom-Json
    } catch {
        throw "[AWX][learning-ops-smoke] diagnostics-json-invalid status=$([int]$resp.StatusCode) contentType=application/json contentLength=$($content.Length)"
    }
    return @{ Status = [int]$resp.StatusCode; Body = $body }
}

function Assert-Eq($Actual, $Expected, [string]$Label) {
    if ([string]$Actual -ne [string]$Expected) {
        throw "[AWX][learning-ops-smoke] $Label expected=$Expected actual=$Actual"
    }
}

function Assert-True($Condition, [string]$Label) {
    if (-not $Condition) {
        throw "[AWX][learning-ops-smoke] assertion failed: $Label"
    }
}

function Wait-ForCollectorFile {
    $deadline = (Get-Date).AddSeconds($CollectorTimeoutSeconds)
    while ((Get-Date) -lt $deadline) {
        if ((Test-Path $CollectorFile) -and ((Get-Item $CollectorFile).Length -gt 0)) {
            return
        }
        Start-Sleep -Seconds 2
    }
    $collectorOutputName = Split-Path -Leaf $CollectorFile
    throw "[AWX][learning-ops-smoke] collector output timeout outputFileHash=$(Hash-Value $collectorOutputName) outputFileLength=$($collectorOutputName.Length)"
}

$app = $null
try {
    New-SeedDatabase
    Set-SmokeEnv
    $app = Start-SmokeApp
    Wait-ForHttp $app

    Wait-ForCollectorFile
    $overview = Invoke-Json "/api/diagnostics/rag/learning-ops/overview?limit=20"
    $loop = Invoke-Json "/api/diagnostics/uaw/autolearn/loop"

    Assert-Eq $overview.Status 200 "overview status"
    Assert-Eq $loop.Status 200 "loop status"
    Assert-Eq $overview.Body.learningOpsCollector.enabled $true "collector enabled"
    Assert-Eq $overview.Body.learningOpsCollector.status "ready_read_only_curation_queue" "collector status"
    Assert-Eq $overview.Body.learningOpsCollector.writesDataset $false "collector writesDataset"
    Assert-Eq $overview.Body.learningOpsCollector.requiresReview $true "collector requiresReview"
    $collectorOutputName = Split-Path -Leaf $CollectorFile
    $collectorProps = @($overview.Body.learningOpsCollector.PSObject.Properties.Name)
    Assert-True (-not ($collectorProps -contains "outputFile")) "collector omits raw output file"
    Assert-Eq $overview.Body.learningOpsCollector.outputFileHash (Hash-Value $collectorOutputName) "collector output file hash"
    Assert-Eq $overview.Body.learningOpsCollector.outputFileLength $collectorOutputName.Length "collector output file length"
    Assert-Eq $overview.Body.learningOpsCollector.outputPathHash (Hash-Value $CollectorFile) "collector output hash"
    Assert-Eq $overview.Body.opsLedger.datasetPipelineQueue.status "ready" "queue status"
    Assert-True ([int]$overview.Body.opsLedger.datasetPipelineQueue.itemCount -ge 1) "queue has candidates"
    Assert-Eq $overview.Body.opsLedger.datasetPipelineQueue.items[0].action "demote_heavy_work" "queue action"
    Assert-Eq $loop.Body.nodeProfile.node.role "macmini-control-plane" "loop node role"
    Assert-Eq $loop.Body.nodeProfile.learningLoop.learningOpsCollectorEnabled $true "loop collector enabled"
    Assert-Eq $loop.Body.nodeProfile.selfLearningBridge.datasetPipeline.collectorOutputPathHash (Hash-Value $CollectorFile) "loop collector hash"

    $lastLine = Get-Content -LiteralPath $CollectorFile -Tail 1
    $record = $lastLine | ConvertFrom-Json
    Assert-Eq $record.checkpoint "[AWX][learning-ops][collector]" "jsonl checkpoint"
    Assert-Eq $record.writesDataset $false "jsonl writesDataset"
    Assert-Eq $record.requiresReview $true "jsonl requiresReview"
    Assert-True ([int]$record.itemCount -ge 1) "jsonl has items"
    Assert-Eq $record.items[0].action "demote_heavy_work" "jsonl action"
    Assert-Eq $record.items[0].gpuAdmission.hardwareReason "gpu_memory_pressure" "jsonl gpu reason"

    $combined = ($overview.Body | ConvertTo-Json -Depth 20 -Compress) +
            ($loop.Body | ConvertTo-Json -Depth 20 -Compress) +
            (Get-Content -LiteralPath $CollectorFile -Raw)
    foreach ($forbidden in @($SeedSecret, $AdminToken, $TempRoot, $DbFile, $CollectorFile)) {
        if ($combined.Contains($forbidden)) {
            throw "[AWX][learning-ops-smoke] leaked forbidden smoke value: $(Redact-Text $forbidden)"
        }
    }
    $runtimeLeakSurface = $combined +
            (Get-Content -LiteralPath $app.OutLog -Raw -ErrorAction SilentlyContinue) +
            (Get-Content -LiteralPath $app.ErrLog -Raw -ErrorAction SilentlyContinue)
    if ($runtimeLeakSurface.Contains($AdminToken)) {
        throw "[AWX][learning-ops-smoke] leaked admin token"
    }
    if ($runtimeLeakSurface -match '(?i)X-Admin-Token\s*:') {
        throw "[AWX][learning-ops-smoke] leaked admin-token header"
    }

    Write-Host "[AWX][learning-ops-smoke] OK node=macmini-control-plane collector=written queue=ready writesDataset=false requiresReview=true adminTokenPresent=true adminTokenFingerprint=$(Hash-Value $AdminToken) outputHash=$((Hash-Value $CollectorFile))"
} finally {
    Stop-SmokeApp $app
    Clear-SmokeEnv
    Remove-Item -LiteralPath $TempRoot -Recurse -Force -ErrorAction SilentlyContinue
}
